name: Add @base on Push

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    if: (!(contains(github.event.commits[0].message, '[AUTO]')))

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get changed files
      id: getfile
      run: |
        files=$(git diff-tree --no-commit-id --name-only -r $(git log -n 1 --pretty=format:"%H") | grep ".ttl$")
        echo "::set-output name=files::$files"
    
    - name: Run Python script on changed files
      run: |
        IFS=' ' read -ra ADDR <<< "${{ steps.getfile.outputs.files }}"
        for file in "${ADDR[@]}"; do
          python add-base.py "$file"

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<steve@steveray.com>"
            
    - name: Commit and Push changes
      run: |
         git add -u  # Adds only modified files to the staging area
         git commit -m "Updated .ttl files with base URI [AUTO]"
         git push    
         done
